
server:
  port: 8889
#spring\u914D\u7F6E
spring:
  #1.\u5E94\u7528\u914D\u7F6E
  application:
    name: dubbo-consumer #\u6307\u5B9A\u670D\u52A1\u540D
  #3.dubbo\u914D\u7F6E
  dubbo:
      registry: zookeeper://139.196.200.54:2181
      server: true